### ISSUE TITLE
Opening Custom controls settings crashes Visual Studio

### ISSUE THREAD

**Issue by bjorndaniel** [madskristensen/DialToolsForVS#23]
### Installed product versions
- Visual Studio: Professional 15.8.0 preview 2
- This extension: 0.7.58

### Description
Searching for commands in the Custom Controls options window crashes Visual Studio

### Steps to recreate
1. Open Tools -> Options 
2. Open Surface Dial -> Custom controls
3. Type something in the search box
4. Visual studio crashes

### Current behavior
Searching for a command to assign to the dial crashes VS

### Expected behavior
Searching should filter the available commands and show them in the list

**Comment by bjorndaniel** [comment]
I will look into this and see if I can provide a fix

**Comment by xperiandri** [comment]
So this is fixed now, right?

**Comment by bjorndaniel** [comment]
@xperiandri Yes! Closing this, thanks for the awesome work!
Fixed in #26
