### ISSUE TITLE
Debug could be enhanced in design mode

### ISSUE THREAD

**Issue by joj** [madskristensen/DialToolsForVS#3]
When not debugging, Debug does the following:
Click: Set/Unset breakpoint
Rotate Right: Scroll
Rotate Left: Scroll

I think it'll be way more useful to have:
Click: Set/Unset breakpoint
Rotate Right: Navigate to next breakpoint
Rotate Left: Navigate to previous breakpoint

I have code for that (I started a Dial extension but never completed it) I can contribute if you like this idea.

Another option is to have a Breakpoint menu and then Debug would be:
Click: Start (this I really really want :) )
Rotate Right/Left: Scroll 

If we do the second option, on Debug Mode my preference would be (when paused):
Click: Continue
Rotate Right: Step Into
Rotate Left: Step Out

I love the feel of pressing the dial, like a pressing a huge button. I think it's more awesome when that huge button does huge actions (like start and continue).

**Comment by madskristensen** [comment]
Yes, that is a good idea. I like the first option. Starting debugging on click is not something I'm totally happy with. Ideally, I'd love for all this to be configurable, but for now let's go with option 1.

If you want to send a PR then please do so. That would be awesome

**Comment by justcla** [comment]
Can I chime in?

Yes - big button big actions! :-D

I propose:
- Double-Click to Start debugging (when no debug running)
- Single-Click to Pause debugging (when in running state)
- Double-Click to Stop debugging (when in running state)
- Double-Click to Continue/Play (when in paused state)

If only we could use the Double-Click option. :-(
