### ISSUE TITLE
Scroll to Find results

### ISSUE THREAD

**Issue by bjorndaniel** [madskristensen/DialToolsForVS#7]
Not an issue but a question.
I cloned the repo and added a menu option called Find with the below functionality:

- Click to open Edit.FindInFiles
- Right scroll to do Edit.GoToNextLocation
- Left scroll to do Edit.GoToPrevLocation

Is this something that you would consider adding if I submit a PR?

**Comment by markmonster** [comment]
Sounds like a good addition to the DialTools.

**Comment by madskristensen** [comment]
Great idea. Yes, I'll definitely take the PR

**Comment by xperiandri** [comment]
Looks like it has been implemented and merged?

**Comment by bjorndaniel** [comment]
@xperiandri Yeah, I just have the memory of a gold fish...
